### PR TITLE
skip husky install

### PR DESCRIPTION
**Pull request by nonoakij**
## Summary
- bump husky version to v8
- skip husky install
-  remove pinst
    - Viron use npm and changed from postinstall to prepare
    - https://github.com/typicode/pinst

## Checklist
- [ ] [changeset file(s)](https://github.com/changesets/changesets/blob/main/docs/adding-a-changeset.md) included

### CODE REVIEW

**Comment by ejithon** [comment]
As mentioned below, it seems to changed the life cycle scripts changed to prepare from postinstall. https://github.com/typicode/husky#usage

**Comment by nonoakij** [comment]
> As mentioned below, it seems to changed the life cycle scripts changed to prepare from postinstall. https://github.com/typicode/husky#usage

It seems that changes have been made in https://github.com/typicode/husky/pull/890 .
I will look into the reason behind them.

**Comment by nonoakij** [comment]
https://github.com/typicode/husky/issues/884

**Review by h8570rg — APPROVED** [review]

**Review by h8570rg — APPROVED** [review]

**Review by ejithon — APPROVED** [review]
LGTM !

**Pull request merged**
